@ECHO OFF

@REM BASE
SET _COLOR_RESET=[0m
SET _COLOR_BOLD=[1m
SET _COLOR_UNDERLINE=[4m
SET _COLOR_INVERSE=[7m
SET _COLOR_STRONG=[101;93m
SET _COLOR_MENU=[7;31m
SET _COLOR_ERROR=[101m

@REM NFC (NORMAL FOREGROUND COLORS)
SET _COLOR_NFC_BLACK=[30m
SET _COLOR_NFC_RED=[31m
SET _COLOR_NFC_GREEN=[32m
SET _COLOR_NFC_YELLOW=[33m
SET _COLOR_NFC_BLUE=[34m
SET _COLOR_NFC_MAGENTA=[35m
SET _COLOR_NFC_CYAN=[36m
SET _COLOR_NFC_WHITE=[37m

@REM NBC (NORMAL BACKGROUND COLORS)
SET _COLOR_NBC_BLACK=[40m
SET _COLOR_NBC_RED=[41m
SET _COLOR_NBC_GREEN=[42m
SET _COLOR_NBC_YELLOW=[43m
SET _COLOR_NBC_BLUE=[44m
SET _COLOR_NBC_MAGENTA=[45m
SET _COLOR_NBC_CYAN=[46m
SET _COLOR_NBC_WHITE=[47m

@REM SFC (STRONG FOREGROUND COLORS)
SET _COLOR_SFC_GREY=[90m
SET _COLOR_SFC_RED=[91m
SET _COLOR_SFC_GREEN=[92m
SET _COLOR_SFC_YELLOW=[93m
SET _COLOR_SFC_BLUE=[94m
SET _COLOR_SFC_MAGENTA=[95m
SET _COLOR_SFC_CYAN=[96m
SET _COLOR_SFC_WHITE=[97m

@REM SBC (STRONG BACKGROUND COLORS)
SET _COLOR_SBC_BLACK=[100m
SET _COLOR_SBC_RED=[101m
SET _COLOR_SBC_GREEN=[102m
SET _COLOR_SBC_YELLOW=[103m
SET _COLOR_SBC_BLUE=[104m
SET _COLOR_SBC_MAGENTA=[105m
SET _COLOR_SBC_CYAN=[106m
SET _COLOR_SBC_WHITE=[107m
